# Generated by Django 4.1.2 on 2022-11-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adresse',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AddField(
            model_name='client',
            name='adressemail',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='details',
            field=models.ManyToManyField(blank=True, help_text='Select a genre for this book', null=True, related_name='commodite', to='immoapp.commodite'),
        ),
    ]
