# Generated by Django 4.1.2 on 2022-11-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immoapp', '0003_remove_client_adressemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
    ]
