# Generated by Django 4.1.2 on 2022-11-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immoapp', '0004_client_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
        migrations.AlterField(
            model_name='immagedb',
            name='img',
            field=models.ImageField(blank=True, help_text='Sélectionner une image svp..', upload_to='immoapp/img_database/'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='details',
            field=models.ManyToManyField(blank=True, help_text='Select a genre for this book', related_name='commodite', to='immoapp.commodite'),
        ),
    ]
