# Generated by Django 4.1.2 on 2022-11-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immoapp', '0005_remove_client_slug_alter_immagedb_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertname', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30, null=True, unique=True)),
                ('lieux', models.CharField(blank=True, max_length=15, null=True)),
                ('typebien', models.CharField(blank=True, max_length=15, null=True)),
                ('typetransaction', models.CharField(blank=True, max_length=15, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('typecontact', models.CharField(blank=True, max_length=15, null=True)),
                ('alertcontact', models.CharField(blank=True, max_length=15, null=True)),
                ('commentaire', models.TextField(blank=True, verbose_name='C')),
            ],
        ),
    ]
