# Generated by Django 4.1.2 on 2022-11-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immoapp', '0006_clientalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientalert',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Information supplémentaire:'),
        ),
    ]
