# Generated by Django 4.1.2 on 2022-11-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immoapp', '0009_clientalert_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientalert',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
