# Generated by Django 4.1.2 on 2022-11-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immoapp', '0010_alter_clientalert_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientalert',
            name='created',
        ),
    ]
