# Generated by Django 4.1.2 on 2022-11-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immoapp', '0011_remove_clientalert_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientalert',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
