# Generated by Django 4.1.2 on 2022-11-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immoapp', '0012_clientalert_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientalert',
            name='created',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
