# Generated by Django 4.1.2 on 2022-11-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immoapp', '0013_alter_clientalert_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientalert',
            name='alertcontact',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
    ]
