# Generated by Django 4.1.2 on 2022-11-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immoapp', '0014_alter_clientalert_alertcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobilier',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
